### PR TITLE
v2 (German)

### PR DESCRIPTION
**Pull request by felbinger**
Due to many requests I have decided to continue this guide in German. I am sorry for all international people who used it in the past. I do not have the time to maintain both versions, feel free to create issues asking for things you don't understand with automatic translation.

### CODE REVIEW

**Comment by felbinger** [comment]
I am still too stupid to handle git, how the hell did I delete this branch :thinking:

**Comment by felbinger** [comment]
I have no fucking clue, why this branch gets deleted all the time... @MarcelCoding any ideas? I'm not clicking on any buttons or something else.  Just pushed my changes using the git cli.

**Comment by MarcelCoding** [comment]
idk, maybe with some special strange git command that you execute?

**Comment by felbinger** [comment]
I can't even reopen this pr ... wtf?!

**Comment by felbinger** [comment]
I have no fucking clue why the hell this isn't working - I'm going to merge this pr now even though it isn't finished.

**Pull request merged**
